disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    - force_try
    - force_cast
    - function_body_length
    - cyclomatic_complexity
    - type_name
    - legacy_constructor
    - shorthand_operator
    - large_tuple
    - for_where
    - implicit_getter
    - discarded_notification_center_observer
    - compiler_protocol_init
excluded:
    - Pods

line_length: 600
type_body_length: 450
file_length: 700

variable_name:
  min_length:
    warning: 1
  max_length:
    warning: 50
